setwd("C:/Users/USER/Desktop/DataProcessingLabs/PT")
data <- read.csv("best_selling_artists.csv")
head(data)
tail(data)
subset(data, Country == "Barbados")
mean(data$Year)
sd(data$Year)
var(data$Year)

plot(data$Year, main = "Main Plot")
hist(data$Year, main = "Histogram")
h1 <- hist(data$Year, main = "Histogram & Polygon")
lines(h1$counts ~ h1$mids, col = "red")
boxplot(data$Year, main = "Boxplot")